// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package eu.flutter.netguard;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class NativeBridge {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum RuleType {
    BLACKLIST(0),
    WHITELIST(1);

    final int index;

    RuleType(final int index) {
      this.index = index;
    }
  }

  /**
   * MODELS
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class VpnConfig {
    /** Identifier for the session to allow matching traffic log to session */
    private @NonNull String session;

    public @NonNull String getSession() {
      return session;
    }

    public void setSession(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"session\" is null.");
      }
      this.session = setterArg;
    }

    /** List of PackageNames that are filtered by the firewall */
    private @NonNull List<String> filteredPackages;

    public @NonNull List<String> getFilteredPackages() {
      return filteredPackages;
    }

    public void setFilteredPackages(@NonNull List<String> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"filteredPackages\" is null.");
      }
      this.filteredPackages = setterArg;
    }

    /** path of the sqlite database, so native code can read from it directly */
    private @NonNull String dbPath;

    public @NonNull String getDbPath() {
      return dbPath;
    }

    public void setDbPath(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dbPath\" is null.");
      }
      this.dbPath = setterArg;
    }

    /** defines if the traffic should be logged. This enables analytics, but may increase battery usage. */
    private @NonNull Boolean logTraffic;

    public @NonNull Boolean getLogTraffic() {
      return logTraffic;
    }

    public void setLogTraffic(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"logTraffic\" is null.");
      }
      this.logTraffic = setterArg;
    }

    /**
     * If this is set, the firewall does not block the traffic, but just observes it.
     * It then logs whether or not it would usually block certain packets.
     * Can be useful to understand the potential impact of the firewall.
     */
    private @NonNull Boolean observeOnly;

    public @NonNull Boolean getObserveOnly() {
      return observeOnly;
    }

    public void setObserveOnly(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"observeOnly\" is null.");
      }
      this.observeOnly = setterArg;
    }

    private @NonNull Long logLevel;

    public @NonNull Long getLogLevel() {
      return logLevel;
    }

    public void setLogLevel(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"logLevel\" is null.");
      }
      this.logLevel = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    VpnConfig() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      VpnConfig that = (VpnConfig) o;
      return session.equals(that.session) && filteredPackages.equals(that.filteredPackages) && dbPath.equals(that.dbPath) && logTraffic.equals(that.logTraffic) && observeOnly.equals(that.observeOnly) && logLevel.equals(that.logLevel);
    }

    @Override
    public int hashCode() {
      return Objects.hash(session, filteredPackages, dbPath, logTraffic, observeOnly, logLevel);
    }

    public static final class Builder {

      private @Nullable String session;

      @CanIgnoreReturnValue
      public @NonNull Builder setSession(@NonNull String setterArg) {
        this.session = setterArg;
        return this;
      }

      private @Nullable List<String> filteredPackages;

      @CanIgnoreReturnValue
      public @NonNull Builder setFilteredPackages(@NonNull List<String> setterArg) {
        this.filteredPackages = setterArg;
        return this;
      }

      private @Nullable String dbPath;

      @CanIgnoreReturnValue
      public @NonNull Builder setDbPath(@NonNull String setterArg) {
        this.dbPath = setterArg;
        return this;
      }

      private @Nullable Boolean logTraffic;

      @CanIgnoreReturnValue
      public @NonNull Builder setLogTraffic(@NonNull Boolean setterArg) {
        this.logTraffic = setterArg;
        return this;
      }

      private @Nullable Boolean observeOnly;

      @CanIgnoreReturnValue
      public @NonNull Builder setObserveOnly(@NonNull Boolean setterArg) {
        this.observeOnly = setterArg;
        return this;
      }

      private @Nullable Long logLevel;

      @CanIgnoreReturnValue
      public @NonNull Builder setLogLevel(@NonNull Long setterArg) {
        this.logLevel = setterArg;
        return this;
      }

      public @NonNull VpnConfig build() {
        VpnConfig pigeonReturn = new VpnConfig();
        pigeonReturn.setSession(session);
        pigeonReturn.setFilteredPackages(filteredPackages);
        pigeonReturn.setDbPath(dbPath);
        pigeonReturn.setLogTraffic(logTraffic);
        pigeonReturn.setObserveOnly(observeOnly);
        pigeonReturn.setLogLevel(logLevel);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(session);
      toListResult.add(filteredPackages);
      toListResult.add(dbPath);
      toListResult.add(logTraffic);
      toListResult.add(observeOnly);
      toListResult.add(logLevel);
      return toListResult;
    }

    static @NonNull VpnConfig fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      VpnConfig pigeonResult = new VpnConfig();
      Object session = pigeonVar_list.get(0);
      pigeonResult.setSession((String) session);
      Object filteredPackages = pigeonVar_list.get(1);
      pigeonResult.setFilteredPackages((List<String>) filteredPackages);
      Object dbPath = pigeonVar_list.get(2);
      pigeonResult.setDbPath((String) dbPath);
      Object logTraffic = pigeonVar_list.get(3);
      pigeonResult.setLogTraffic((Boolean) logTraffic);
      Object observeOnly = pigeonVar_list.get(4);
      pigeonResult.setObserveOnly((Boolean) observeOnly);
      Object logLevel = pigeonVar_list.get(5);
      pigeonResult.setLogLevel((Long) logLevel);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Application {
    private @NonNull Long uid;

    public @NonNull Long getUid() {
      return uid;
    }

    public void setUid(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"uid\" is null.");
      }
      this.uid = setterArg;
    }

    private @NonNull String packageName;

    public @NonNull String getPackageName() {
      return packageName;
    }

    public void setPackageName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packageName\" is null.");
      }
      this.packageName = setterArg;
    }

    private @NonNull String label;

    public @NonNull String getLabel() {
      return label;
    }

    public void setLabel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"label\" is null.");
      }
      this.label = setterArg;
    }

    private @NonNull String version;

    public @NonNull String getVersion() {
      return version;
    }

    public void setVersion(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"version\" is null.");
      }
      this.version = setterArg;
    }

    private @Nullable byte[] icon;

    public @Nullable byte[] getIcon() {
      return icon;
    }

    public void setIcon(@Nullable byte[] setterArg) {
      this.icon = setterArg;
    }

    private @NonNull Boolean system;

    public @NonNull Boolean getSystem() {
      return system;
    }

    public void setSystem(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"system\" is null.");
      }
      this.system = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    Application() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Application that = (Application) o;
      return uid.equals(that.uid) && packageName.equals(that.packageName) && label.equals(that.label) && version.equals(that.version) && Arrays.equals(icon, that.icon) && system.equals(that.system);
    }

    @Override
    public int hashCode() {
      int pigeonVar_result = Objects.hash(uid, packageName, label, version, system);
      pigeonVar_result = 31 * pigeonVar_result + Arrays.hashCode(icon);
      return pigeonVar_result;
    }

    public static final class Builder {

      private @Nullable Long uid;

      @CanIgnoreReturnValue
      public @NonNull Builder setUid(@NonNull Long setterArg) {
        this.uid = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@NonNull String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable String label;

      @CanIgnoreReturnValue
      public @NonNull Builder setLabel(@NonNull String setterArg) {
        this.label = setterArg;
        return this;
      }

      private @Nullable String version;

      @CanIgnoreReturnValue
      public @NonNull Builder setVersion(@NonNull String setterArg) {
        this.version = setterArg;
        return this;
      }

      private @Nullable byte[] icon;

      @CanIgnoreReturnValue
      public @NonNull Builder setIcon(@Nullable byte[] setterArg) {
        this.icon = setterArg;
        return this;
      }

      private @Nullable Boolean system;

      @CanIgnoreReturnValue
      public @NonNull Builder setSystem(@NonNull Boolean setterArg) {
        this.system = setterArg;
        return this;
      }

      public @NonNull Application build() {
        Application pigeonReturn = new Application();
        pigeonReturn.setUid(uid);
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setLabel(label);
        pigeonReturn.setVersion(version);
        pigeonReturn.setIcon(icon);
        pigeonReturn.setSystem(system);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(uid);
      toListResult.add(packageName);
      toListResult.add(label);
      toListResult.add(version);
      toListResult.add(icon);
      toListResult.add(system);
      return toListResult;
    }

    static @NonNull Application fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Application pigeonResult = new Application();
      Object uid = pigeonVar_list.get(0);
      pigeonResult.setUid((Long) uid);
      Object packageName = pigeonVar_list.get(1);
      pigeonResult.setPackageName((String) packageName);
      Object label = pigeonVar_list.get(2);
      pigeonResult.setLabel((String) label);
      Object version = pigeonVar_list.get(3);
      pigeonResult.setVersion((String) version);
      Object icon = pigeonVar_list.get(4);
      pigeonResult.setIcon((byte[]) icon);
      Object system = pigeonVar_list.get(5);
      pigeonResult.setSystem((Boolean) system);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ApplicationSetting {
    private @NonNull String packageName;

    public @NonNull String getPackageName() {
      return packageName;
    }

    public void setPackageName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packageName\" is null.");
      }
      this.packageName = setterArg;
    }

    private @NonNull Boolean filter;

    public @NonNull Boolean getFilter() {
      return filter;
    }

    public void setFilter(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"filter\" is null.");
      }
      this.filter = setterArg;
    }

    private @NonNull Boolean blockAll;

    public @NonNull Boolean getBlockAll() {
      return blockAll;
    }

    public void setBlockAll(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"blockAll\" is null.");
      }
      this.blockAll = setterArg;
    }

    private @NonNull Boolean blockQuic;

    public @NonNull Boolean getBlockQuic() {
      return blockQuic;
    }

    public void setBlockQuic(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"blockQuic\" is null.");
      }
      this.blockQuic = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ApplicationSetting() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ApplicationSetting that = (ApplicationSetting) o;
      return packageName.equals(that.packageName) && filter.equals(that.filter) && blockAll.equals(that.blockAll) && blockQuic.equals(that.blockQuic);
    }

    @Override
    public int hashCode() {
      return Objects.hash(packageName, filter, blockAll, blockQuic);
    }

    public static final class Builder {

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@NonNull String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable Boolean filter;

      @CanIgnoreReturnValue
      public @NonNull Builder setFilter(@NonNull Boolean setterArg) {
        this.filter = setterArg;
        return this;
      }

      private @Nullable Boolean blockAll;

      @CanIgnoreReturnValue
      public @NonNull Builder setBlockAll(@NonNull Boolean setterArg) {
        this.blockAll = setterArg;
        return this;
      }

      private @Nullable Boolean blockQuic;

      @CanIgnoreReturnValue
      public @NonNull Builder setBlockQuic(@NonNull Boolean setterArg) {
        this.blockQuic = setterArg;
        return this;
      }

      public @NonNull ApplicationSetting build() {
        ApplicationSetting pigeonReturn = new ApplicationSetting();
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setFilter(filter);
        pigeonReturn.setBlockAll(blockAll);
        pigeonReturn.setBlockQuic(blockQuic);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(packageName);
      toListResult.add(filter);
      toListResult.add(blockAll);
      toListResult.add(blockQuic);
      return toListResult;
    }

    static @NonNull ApplicationSetting fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ApplicationSetting pigeonResult = new ApplicationSetting();
      Object packageName = pigeonVar_list.get(0);
      pigeonResult.setPackageName((String) packageName);
      Object filter = pigeonVar_list.get(1);
      pigeonResult.setFilter((Boolean) filter);
      Object blockAll = pigeonVar_list.get(2);
      pigeonResult.setBlockAll((Boolean) blockAll);
      Object blockQuic = pigeonVar_list.get(3);
      pigeonResult.setBlockQuic((Boolean) blockQuic);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Packet {
    private @NonNull Long time;

    public @NonNull Long getTime() {
      return time;
    }

    public void setTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"time\" is null.");
      }
      this.time = setterArg;
    }

    private @NonNull Long version;

    public @NonNull Long getVersion() {
      return version;
    }

    public void setVersion(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"version\" is null.");
      }
      this.version = setterArg;
    }

    private @NonNull Long protocol;

    public @NonNull Long getProtocol() {
      return protocol;
    }

    public void setProtocol(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"protocol\" is null.");
      }
      this.protocol = setterArg;
    }

    private @NonNull String flags;

    public @NonNull String getFlags() {
      return flags;
    }

    public void setFlags(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"flags\" is null.");
      }
      this.flags = setterArg;
    }

    private @NonNull String saddr;

    public @NonNull String getSaddr() {
      return saddr;
    }

    public void setSaddr(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"saddr\" is null.");
      }
      this.saddr = setterArg;
    }

    private @NonNull Long sport;

    public @NonNull Long getSport() {
      return sport;
    }

    public void setSport(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"sport\" is null.");
      }
      this.sport = setterArg;
    }

    private @NonNull String daddr;

    public @NonNull String getDaddr() {
      return daddr;
    }

    public void setDaddr(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"daddr\" is null.");
      }
      this.daddr = setterArg;
    }

    private @NonNull Long dport;

    public @NonNull Long getDport() {
      return dport;
    }

    public void setDport(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dport\" is null.");
      }
      this.dport = setterArg;
    }

    private @NonNull String data;

    public @NonNull String getData() {
      return data;
    }

    public void setData(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"data\" is null.");
      }
      this.data = setterArg;
    }

    private @NonNull Long uid;

    public @NonNull Long getUid() {
      return uid;
    }

    public void setUid(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"uid\" is null.");
      }
      this.uid = setterArg;
    }

    private @Nullable String packageName;

    public @Nullable String getPackageName() {
      return packageName;
    }

    public void setPackageName(@Nullable String setterArg) {
      this.packageName = setterArg;
    }

    private @NonNull Boolean allowed;

    public @NonNull Boolean getAllowed() {
      return allowed;
    }

    public void setAllowed(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"allowed\" is null.");
      }
      this.allowed = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    Packet() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Packet that = (Packet) o;
      return time.equals(that.time) && version.equals(that.version) && protocol.equals(that.protocol) && flags.equals(that.flags) && saddr.equals(that.saddr) && sport.equals(that.sport) && daddr.equals(that.daddr) && dport.equals(that.dport) && data.equals(that.data) && uid.equals(that.uid) && Objects.equals(packageName, that.packageName) && allowed.equals(that.allowed);
    }

    @Override
    public int hashCode() {
      return Objects.hash(time, version, protocol, flags, saddr, sport, daddr, dport, data, uid, packageName, allowed);
    }

    public static final class Builder {

      private @Nullable Long time;

      @CanIgnoreReturnValue
      public @NonNull Builder setTime(@NonNull Long setterArg) {
        this.time = setterArg;
        return this;
      }

      private @Nullable Long version;

      @CanIgnoreReturnValue
      public @NonNull Builder setVersion(@NonNull Long setterArg) {
        this.version = setterArg;
        return this;
      }

      private @Nullable Long protocol;

      @CanIgnoreReturnValue
      public @NonNull Builder setProtocol(@NonNull Long setterArg) {
        this.protocol = setterArg;
        return this;
      }

      private @Nullable String flags;

      @CanIgnoreReturnValue
      public @NonNull Builder setFlags(@NonNull String setterArg) {
        this.flags = setterArg;
        return this;
      }

      private @Nullable String saddr;

      @CanIgnoreReturnValue
      public @NonNull Builder setSaddr(@NonNull String setterArg) {
        this.saddr = setterArg;
        return this;
      }

      private @Nullable Long sport;

      @CanIgnoreReturnValue
      public @NonNull Builder setSport(@NonNull Long setterArg) {
        this.sport = setterArg;
        return this;
      }

      private @Nullable String daddr;

      @CanIgnoreReturnValue
      public @NonNull Builder setDaddr(@NonNull String setterArg) {
        this.daddr = setterArg;
        return this;
      }

      private @Nullable Long dport;

      @CanIgnoreReturnValue
      public @NonNull Builder setDport(@NonNull Long setterArg) {
        this.dport = setterArg;
        return this;
      }

      private @Nullable String data;

      @CanIgnoreReturnValue
      public @NonNull Builder setData(@NonNull String setterArg) {
        this.data = setterArg;
        return this;
      }

      private @Nullable Long uid;

      @CanIgnoreReturnValue
      public @NonNull Builder setUid(@NonNull Long setterArg) {
        this.uid = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@Nullable String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable Boolean allowed;

      @CanIgnoreReturnValue
      public @NonNull Builder setAllowed(@NonNull Boolean setterArg) {
        this.allowed = setterArg;
        return this;
      }

      public @NonNull Packet build() {
        Packet pigeonReturn = new Packet();
        pigeonReturn.setTime(time);
        pigeonReturn.setVersion(version);
        pigeonReturn.setProtocol(protocol);
        pigeonReturn.setFlags(flags);
        pigeonReturn.setSaddr(saddr);
        pigeonReturn.setSport(sport);
        pigeonReturn.setDaddr(daddr);
        pigeonReturn.setDport(dport);
        pigeonReturn.setData(data);
        pigeonReturn.setUid(uid);
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setAllowed(allowed);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(12);
      toListResult.add(time);
      toListResult.add(version);
      toListResult.add(protocol);
      toListResult.add(flags);
      toListResult.add(saddr);
      toListResult.add(sport);
      toListResult.add(daddr);
      toListResult.add(dport);
      toListResult.add(data);
      toListResult.add(uid);
      toListResult.add(packageName);
      toListResult.add(allowed);
      return toListResult;
    }

    static @NonNull Packet fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Packet pigeonResult = new Packet();
      Object time = pigeonVar_list.get(0);
      pigeonResult.setTime((Long) time);
      Object version = pigeonVar_list.get(1);
      pigeonResult.setVersion((Long) version);
      Object protocol = pigeonVar_list.get(2);
      pigeonResult.setProtocol((Long) protocol);
      Object flags = pigeonVar_list.get(3);
      pigeonResult.setFlags((String) flags);
      Object saddr = pigeonVar_list.get(4);
      pigeonResult.setSaddr((String) saddr);
      Object sport = pigeonVar_list.get(5);
      pigeonResult.setSport((Long) sport);
      Object daddr = pigeonVar_list.get(6);
      pigeonResult.setDaddr((String) daddr);
      Object dport = pigeonVar_list.get(7);
      pigeonResult.setDport((Long) dport);
      Object data = pigeonVar_list.get(8);
      pigeonResult.setData((String) data);
      Object uid = pigeonVar_list.get(9);
      pigeonResult.setUid((Long) uid);
      Object packageName = pigeonVar_list.get(10);
      pigeonResult.setPackageName((String) packageName);
      Object allowed = pigeonVar_list.get(11);
      pigeonResult.setAllowed((Boolean) allowed);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ResourceRecord {
    private @NonNull Long time;

    public @NonNull Long getTime() {
      return time;
    }

    public void setTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"time\" is null.");
      }
      this.time = setterArg;
    }

    private @NonNull String qName;

    public @NonNull String getQName() {
      return qName;
    }

    public void setQName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"qName\" is null.");
      }
      this.qName = setterArg;
    }

    private @NonNull String aName;

    public @NonNull String getAName() {
      return aName;
    }

    public void setAName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"aName\" is null.");
      }
      this.aName = setterArg;
    }

    private @NonNull String resource;

    public @NonNull String getResource() {
      return resource;
    }

    public void setResource(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"resource\" is null.");
      }
      this.resource = setterArg;
    }

    private @Nullable Long ttl;

    public @Nullable Long getTtl() {
      return ttl;
    }

    public void setTtl(@Nullable Long setterArg) {
      this.ttl = setterArg;
    }

    private @Nullable Long uid;

    public @Nullable Long getUid() {
      return uid;
    }

    public void setUid(@Nullable Long setterArg) {
      this.uid = setterArg;
    }

    private @Nullable String packageName;

    public @Nullable String getPackageName() {
      return packageName;
    }

    public void setPackageName(@Nullable String setterArg) {
      this.packageName = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ResourceRecord() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ResourceRecord that = (ResourceRecord) o;
      return time.equals(that.time) && qName.equals(that.qName) && aName.equals(that.aName) && resource.equals(that.resource) && Objects.equals(ttl, that.ttl) && Objects.equals(uid, that.uid) && Objects.equals(packageName, that.packageName);
    }

    @Override
    public int hashCode() {
      return Objects.hash(time, qName, aName, resource, ttl, uid, packageName);
    }

    public static final class Builder {

      private @Nullable Long time;

      @CanIgnoreReturnValue
      public @NonNull Builder setTime(@NonNull Long setterArg) {
        this.time = setterArg;
        return this;
      }

      private @Nullable String qName;

      @CanIgnoreReturnValue
      public @NonNull Builder setQName(@NonNull String setterArg) {
        this.qName = setterArg;
        return this;
      }

      private @Nullable String aName;

      @CanIgnoreReturnValue
      public @NonNull Builder setAName(@NonNull String setterArg) {
        this.aName = setterArg;
        return this;
      }

      private @Nullable String resource;

      @CanIgnoreReturnValue
      public @NonNull Builder setResource(@NonNull String setterArg) {
        this.resource = setterArg;
        return this;
      }

      private @Nullable Long ttl;

      @CanIgnoreReturnValue
      public @NonNull Builder setTtl(@Nullable Long setterArg) {
        this.ttl = setterArg;
        return this;
      }

      private @Nullable Long uid;

      @CanIgnoreReturnValue
      public @NonNull Builder setUid(@Nullable Long setterArg) {
        this.uid = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@Nullable String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      public @NonNull ResourceRecord build() {
        ResourceRecord pigeonReturn = new ResourceRecord();
        pigeonReturn.setTime(time);
        pigeonReturn.setQName(qName);
        pigeonReturn.setAName(aName);
        pigeonReturn.setResource(resource);
        pigeonReturn.setTtl(ttl);
        pigeonReturn.setUid(uid);
        pigeonReturn.setPackageName(packageName);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(7);
      toListResult.add(time);
      toListResult.add(qName);
      toListResult.add(aName);
      toListResult.add(resource);
      toListResult.add(ttl);
      toListResult.add(uid);
      toListResult.add(packageName);
      return toListResult;
    }

    static @NonNull ResourceRecord fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ResourceRecord pigeonResult = new ResourceRecord();
      Object time = pigeonVar_list.get(0);
      pigeonResult.setTime((Long) time);
      Object qName = pigeonVar_list.get(1);
      pigeonResult.setQName((String) qName);
      Object aName = pigeonVar_list.get(2);
      pigeonResult.setAName((String) aName);
      Object resource = pigeonVar_list.get(3);
      pigeonResult.setResource((String) resource);
      Object ttl = pigeonVar_list.get(4);
      pigeonResult.setTtl((Long) ttl);
      Object uid = pigeonVar_list.get(5);
      pigeonResult.setUid((Long) uid);
      Object packageName = pigeonVar_list.get(6);
      pigeonResult.setPackageName((String) packageName);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Rule {
    private @Nullable String packageName;

    public @Nullable String getPackageName() {
      return packageName;
    }

    public void setPackageName(@Nullable String setterArg) {
      this.packageName = setterArg;
    }

    private @NonNull RuleType type;

    public @NonNull RuleType getType() {
      return type;
    }

    public void setType(@NonNull RuleType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    private @NonNull Boolean shouldBlockQuic;

    public @NonNull Boolean getShouldBlockQuic() {
      return shouldBlockQuic;
    }

    public void setShouldBlockQuic(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"shouldBlockQuic\" is null.");
      }
      this.shouldBlockQuic = setterArg;
    }

    private @NonNull Boolean whitelistExclusive;

    public @NonNull Boolean getWhitelistExclusive() {
      return whitelistExclusive;
    }

    public void setWhitelistExclusive(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"whitelistExclusive\" is null.");
      }
      this.whitelistExclusive = setterArg;
    }

    private @NonNull Map<String, Boolean> hosts;

    public @NonNull Map<String, Boolean> getHosts() {
      return hosts;
    }

    public void setHosts(@NonNull Map<String, Boolean> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"hosts\" is null.");
      }
      this.hosts = setterArg;
    }

    private @NonNull Map<String, Boolean> ips;

    public @NonNull Map<String, Boolean> getIps() {
      return ips;
    }

    public void setIps(@NonNull Map<String, Boolean> setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"ips\" is null.");
      }
      this.ips = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    Rule() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Rule that = (Rule) o;
      return Objects.equals(packageName, that.packageName) && type.equals(that.type) && shouldBlockQuic.equals(that.shouldBlockQuic) && whitelistExclusive.equals(that.whitelistExclusive) && hosts.equals(that.hosts) && ips.equals(that.ips);
    }

    @Override
    public int hashCode() {
      return Objects.hash(packageName, type, shouldBlockQuic, whitelistExclusive, hosts, ips);
    }

    public static final class Builder {

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@Nullable String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable RuleType type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull RuleType setterArg) {
        this.type = setterArg;
        return this;
      }

      private @Nullable Boolean shouldBlockQuic;

      @CanIgnoreReturnValue
      public @NonNull Builder setShouldBlockQuic(@NonNull Boolean setterArg) {
        this.shouldBlockQuic = setterArg;
        return this;
      }

      private @Nullable Boolean whitelistExclusive;

      @CanIgnoreReturnValue
      public @NonNull Builder setWhitelistExclusive(@NonNull Boolean setterArg) {
        this.whitelistExclusive = setterArg;
        return this;
      }

      private @Nullable Map<String, Boolean> hosts;

      @CanIgnoreReturnValue
      public @NonNull Builder setHosts(@NonNull Map<String, Boolean> setterArg) {
        this.hosts = setterArg;
        return this;
      }

      private @Nullable Map<String, Boolean> ips;

      @CanIgnoreReturnValue
      public @NonNull Builder setIps(@NonNull Map<String, Boolean> setterArg) {
        this.ips = setterArg;
        return this;
      }

      public @NonNull Rule build() {
        Rule pigeonReturn = new Rule();
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setType(type);
        pigeonReturn.setShouldBlockQuic(shouldBlockQuic);
        pigeonReturn.setWhitelistExclusive(whitelistExclusive);
        pigeonReturn.setHosts(hosts);
        pigeonReturn.setIps(ips);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(packageName);
      toListResult.add(type);
      toListResult.add(shouldBlockQuic);
      toListResult.add(whitelistExclusive);
      toListResult.add(hosts);
      toListResult.add(ips);
      return toListResult;
    }

    static @NonNull Rule fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Rule pigeonResult = new Rule();
      Object packageName = pigeonVar_list.get(0);
      pigeonResult.setPackageName((String) packageName);
      Object type = pigeonVar_list.get(1);
      pigeonResult.setType((RuleType) type);
      Object shouldBlockQuic = pigeonVar_list.get(2);
      pigeonResult.setShouldBlockQuic((Boolean) shouldBlockQuic);
      Object whitelistExclusive = pigeonVar_list.get(3);
      pigeonResult.setWhitelistExclusive((Boolean) whitelistExclusive);
      Object hosts = pigeonVar_list.get(4);
      pigeonResult.setHosts((Map<String, Boolean>) hosts);
      Object ips = pigeonVar_list.get(5);
      pigeonResult.setIps((Map<String, Boolean>) ips);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class LogEntry {
    private @NonNull Long time;

    public @NonNull Long getTime() {
      return time;
    }

    public void setTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"time\" is null.");
      }
      this.time = setterArg;
    }

    private @NonNull String session;

    public @NonNull String getSession() {
      return session;
    }

    public void setSession(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"session\" is null.");
      }
      this.session = setterArg;
    }

    private @NonNull Object data;

    public @NonNull Object getData() {
      return data;
    }

    public void setData(@NonNull Object setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"data\" is null.");
      }
      this.data = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    LogEntry() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      LogEntry that = (LogEntry) o;
      return time.equals(that.time) && session.equals(that.session) && data.equals(that.data);
    }

    @Override
    public int hashCode() {
      return Objects.hash(time, session, data);
    }

    public static final class Builder {

      private @Nullable Long time;

      @CanIgnoreReturnValue
      public @NonNull Builder setTime(@NonNull Long setterArg) {
        this.time = setterArg;
        return this;
      }

      private @Nullable String session;

      @CanIgnoreReturnValue
      public @NonNull Builder setSession(@NonNull String setterArg) {
        this.session = setterArg;
        return this;
      }

      private @Nullable Object data;

      @CanIgnoreReturnValue
      public @NonNull Builder setData(@NonNull Object setterArg) {
        this.data = setterArg;
        return this;
      }

      public @NonNull LogEntry build() {
        LogEntry pigeonReturn = new LogEntry();
        pigeonReturn.setTime(time);
        pigeonReturn.setSession(session);
        pigeonReturn.setData(data);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(time);
      toListResult.add(session);
      toListResult.add(data);
      return toListResult;
    }

    static @NonNull LogEntry fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      LogEntry pigeonResult = new LogEntry();
      Object time = pigeonVar_list.get(0);
      pigeonResult.setTime((Long) time);
      Object session = pigeonVar_list.get(1);
      pigeonResult.setSession((String) session);
      Object data = pigeonVar_list.get(2);
      pigeonResult.setData(data);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class ErrorLog {
    private @NonNull Long time;

    public @NonNull Long getTime() {
      return time;
    }

    public void setTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"time\" is null.");
      }
      this.time = setterArg;
    }

    private @NonNull String session;

    public @NonNull String getSession() {
      return session;
    }

    public void setSession(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"session\" is null.");
      }
      this.session = setterArg;
    }

    private @NonNull String message;

    public @NonNull String getMessage() {
      return message;
    }

    public void setMessage(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"message\" is null.");
      }
      this.message = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ErrorLog() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ErrorLog that = (ErrorLog) o;
      return time.equals(that.time) && session.equals(that.session) && message.equals(that.message);
    }

    @Override
    public int hashCode() {
      return Objects.hash(time, session, message);
    }

    public static final class Builder {

      private @Nullable Long time;

      @CanIgnoreReturnValue
      public @NonNull Builder setTime(@NonNull Long setterArg) {
        this.time = setterArg;
        return this;
      }

      private @Nullable String session;

      @CanIgnoreReturnValue
      public @NonNull Builder setSession(@NonNull String setterArg) {
        this.session = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@NonNull String setterArg) {
        this.message = setterArg;
        return this;
      }

      public @NonNull ErrorLog build() {
        ErrorLog pigeonReturn = new ErrorLog();
        pigeonReturn.setTime(time);
        pigeonReturn.setSession(session);
        pigeonReturn.setMessage(message);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(time);
      toListResult.add(session);
      toListResult.add(message);
      return toListResult;
    }

    static @NonNull ErrorLog fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ErrorLog pigeonResult = new ErrorLog();
      Object time = pigeonVar_list.get(0);
      pigeonResult.setTime((Long) time);
      Object session = pigeonVar_list.get(1);
      pigeonResult.setSession((String) session);
      Object message = pigeonVar_list.get(2);
      pigeonResult.setMessage((String) message);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class SessionStatistics {
    private @NonNull Long packetCountAllowed;

    public @NonNull Long getPacketCountAllowed() {
      return packetCountAllowed;
    }

    public void setPacketCountAllowed(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packetCountAllowed\" is null.");
      }
      this.packetCountAllowed = setterArg;
    }

    private @NonNull Long packetSizeAllowed;

    public @NonNull Long getPacketSizeAllowed() {
      return packetSizeAllowed;
    }

    public void setPacketSizeAllowed(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packetSizeAllowed\" is null.");
      }
      this.packetSizeAllowed = setterArg;
    }

    private @NonNull Long packetCountBlocked;

    public @NonNull Long getPacketCountBlocked() {
      return packetCountBlocked;
    }

    public void setPacketCountBlocked(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packetCountBlocked\" is null.");
      }
      this.packetCountBlocked = setterArg;
    }

    private @NonNull Long packetSizeBlocked;

    public @NonNull Long getPacketSizeBlocked() {
      return packetSizeBlocked;
    }

    public void setPacketSizeBlocked(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"packetSizeBlocked\" is null.");
      }
      this.packetSizeBlocked = setterArg;
    }

    private @Nullable String mostBlockedPackage;

    public @Nullable String getMostBlockedPackage() {
      return mostBlockedPackage;
    }

    public void setMostBlockedPackage(@Nullable String setterArg) {
      this.mostBlockedPackage = setterArg;
    }

    private @Nullable String mostTrafficPackage;

    public @Nullable String getMostTrafficPackage() {
      return mostTrafficPackage;
    }

    public void setMostTrafficPackage(@Nullable String setterArg) {
      this.mostTrafficPackage = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    SessionStatistics() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      SessionStatistics that = (SessionStatistics) o;
      return packetCountAllowed.equals(that.packetCountAllowed) && packetSizeAllowed.equals(that.packetSizeAllowed) && packetCountBlocked.equals(that.packetCountBlocked) && packetSizeBlocked.equals(that.packetSizeBlocked) && Objects.equals(mostBlockedPackage, that.mostBlockedPackage) && Objects.equals(mostTrafficPackage, that.mostTrafficPackage);
    }

    @Override
    public int hashCode() {
      return Objects.hash(packetCountAllowed, packetSizeAllowed, packetCountBlocked, packetSizeBlocked, mostBlockedPackage, mostTrafficPackage);
    }

    public static final class Builder {

      private @Nullable Long packetCountAllowed;

      @CanIgnoreReturnValue
      public @NonNull Builder setPacketCountAllowed(@NonNull Long setterArg) {
        this.packetCountAllowed = setterArg;
        return this;
      }

      private @Nullable Long packetSizeAllowed;

      @CanIgnoreReturnValue
      public @NonNull Builder setPacketSizeAllowed(@NonNull Long setterArg) {
        this.packetSizeAllowed = setterArg;
        return this;
      }

      private @Nullable Long packetCountBlocked;

      @CanIgnoreReturnValue
      public @NonNull Builder setPacketCountBlocked(@NonNull Long setterArg) {
        this.packetCountBlocked = setterArg;
        return this;
      }

      private @Nullable Long packetSizeBlocked;

      @CanIgnoreReturnValue
      public @NonNull Builder setPacketSizeBlocked(@NonNull Long setterArg) {
        this.packetSizeBlocked = setterArg;
        return this;
      }

      private @Nullable String mostBlockedPackage;

      @CanIgnoreReturnValue
      public @NonNull Builder setMostBlockedPackage(@Nullable String setterArg) {
        this.mostBlockedPackage = setterArg;
        return this;
      }

      private @Nullable String mostTrafficPackage;

      @CanIgnoreReturnValue
      public @NonNull Builder setMostTrafficPackage(@Nullable String setterArg) {
        this.mostTrafficPackage = setterArg;
        return this;
      }

      public @NonNull SessionStatistics build() {
        SessionStatistics pigeonReturn = new SessionStatistics();
        pigeonReturn.setPacketCountAllowed(packetCountAllowed);
        pigeonReturn.setPacketSizeAllowed(packetSizeAllowed);
        pigeonReturn.setPacketCountBlocked(packetCountBlocked);
        pigeonReturn.setPacketSizeBlocked(packetSizeBlocked);
        pigeonReturn.setMostBlockedPackage(mostBlockedPackage);
        pigeonReturn.setMostTrafficPackage(mostTrafficPackage);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(6);
      toListResult.add(packetCountAllowed);
      toListResult.add(packetSizeAllowed);
      toListResult.add(packetCountBlocked);
      toListResult.add(packetSizeBlocked);
      toListResult.add(mostBlockedPackage);
      toListResult.add(mostTrafficPackage);
      return toListResult;
    }

    static @NonNull SessionStatistics fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      SessionStatistics pigeonResult = new SessionStatistics();
      Object packetCountAllowed = pigeonVar_list.get(0);
      pigeonResult.setPacketCountAllowed((Long) packetCountAllowed);
      Object packetSizeAllowed = pigeonVar_list.get(1);
      pigeonResult.setPacketSizeAllowed((Long) packetSizeAllowed);
      Object packetCountBlocked = pigeonVar_list.get(2);
      pigeonResult.setPacketCountBlocked((Long) packetCountBlocked);
      Object packetSizeBlocked = pigeonVar_list.get(3);
      pigeonResult.setPacketSizeBlocked((Long) packetSizeBlocked);
      Object mostBlockedPackage = pigeonVar_list.get(4);
      pigeonResult.setMostBlockedPackage((String) mostBlockedPackage);
      Object mostTrafficPackage = pigeonVar_list.get(5);
      pigeonResult.setMostTrafficPackage((String) mostTrafficPackage);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class TrafficLog {
    private @NonNull Long time;

    public @NonNull Long getTime() {
      return time;
    }

    public void setTime(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"time\" is null.");
      }
      this.time = setterArg;
    }

    private @NonNull String session;

    public @NonNull String getSession() {
      return session;
    }

    public void setSession(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"session\" is null.");
      }
      this.session = setterArg;
    }

    private @NonNull Long protocol;

    public @NonNull Long getProtocol() {
      return protocol;
    }

    public void setProtocol(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"protocol\" is null.");
      }
      this.protocol = setterArg;
    }

    private @NonNull Long dport;

    public @NonNull Long getDport() {
      return dport;
    }

    public void setDport(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"dport\" is null.");
      }
      this.dport = setterArg;
    }

    private @NonNull String ip;

    public @NonNull String getIp() {
      return ip;
    }

    public void setIp(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"ip\" is null.");
      }
      this.ip = setterArg;
    }

    private @Nullable String host;

    public @Nullable String getHost() {
      return host;
    }

    public void setHost(@Nullable String setterArg) {
      this.host = setterArg;
    }

    private @Nullable String packageName;

    public @Nullable String getPackageName() {
      return packageName;
    }

    public void setPackageName(@Nullable String setterArg) {
      this.packageName = setterArg;
    }

    private @NonNull Long size;

    public @NonNull Long getSize() {
      return size;
    }

    public void setSize(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"size\" is null.");
      }
      this.size = setterArg;
    }

    private @NonNull Boolean allowed;

    public @NonNull Boolean getAllowed() {
      return allowed;
    }

    public void setAllowed(@NonNull Boolean setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"allowed\" is null.");
      }
      this.allowed = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    TrafficLog() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      TrafficLog that = (TrafficLog) o;
      return time.equals(that.time) && session.equals(that.session) && protocol.equals(that.protocol) && dport.equals(that.dport) && ip.equals(that.ip) && Objects.equals(host, that.host) && Objects.equals(packageName, that.packageName) && size.equals(that.size) && allowed.equals(that.allowed);
    }

    @Override
    public int hashCode() {
      return Objects.hash(time, session, protocol, dport, ip, host, packageName, size, allowed);
    }

    public static final class Builder {

      private @Nullable Long time;

      @CanIgnoreReturnValue
      public @NonNull Builder setTime(@NonNull Long setterArg) {
        this.time = setterArg;
        return this;
      }

      private @Nullable String session;

      @CanIgnoreReturnValue
      public @NonNull Builder setSession(@NonNull String setterArg) {
        this.session = setterArg;
        return this;
      }

      private @Nullable Long protocol;

      @CanIgnoreReturnValue
      public @NonNull Builder setProtocol(@NonNull Long setterArg) {
        this.protocol = setterArg;
        return this;
      }

      private @Nullable Long dport;

      @CanIgnoreReturnValue
      public @NonNull Builder setDport(@NonNull Long setterArg) {
        this.dport = setterArg;
        return this;
      }

      private @Nullable String ip;

      @CanIgnoreReturnValue
      public @NonNull Builder setIp(@NonNull String setterArg) {
        this.ip = setterArg;
        return this;
      }

      private @Nullable String host;

      @CanIgnoreReturnValue
      public @NonNull Builder setHost(@Nullable String setterArg) {
        this.host = setterArg;
        return this;
      }

      private @Nullable String packageName;

      @CanIgnoreReturnValue
      public @NonNull Builder setPackageName(@Nullable String setterArg) {
        this.packageName = setterArg;
        return this;
      }

      private @Nullable Long size;

      @CanIgnoreReturnValue
      public @NonNull Builder setSize(@NonNull Long setterArg) {
        this.size = setterArg;
        return this;
      }

      private @Nullable Boolean allowed;

      @CanIgnoreReturnValue
      public @NonNull Builder setAllowed(@NonNull Boolean setterArg) {
        this.allowed = setterArg;
        return this;
      }

      public @NonNull TrafficLog build() {
        TrafficLog pigeonReturn = new TrafficLog();
        pigeonReturn.setTime(time);
        pigeonReturn.setSession(session);
        pigeonReturn.setProtocol(protocol);
        pigeonReturn.setDport(dport);
        pigeonReturn.setIp(ip);
        pigeonReturn.setHost(host);
        pigeonReturn.setPackageName(packageName);
        pigeonReturn.setSize(size);
        pigeonReturn.setAllowed(allowed);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(9);
      toListResult.add(time);
      toListResult.add(session);
      toListResult.add(protocol);
      toListResult.add(dport);
      toListResult.add(ip);
      toListResult.add(host);
      toListResult.add(packageName);
      toListResult.add(size);
      toListResult.add(allowed);
      return toListResult;
    }

    static @NonNull TrafficLog fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      TrafficLog pigeonResult = new TrafficLog();
      Object time = pigeonVar_list.get(0);
      pigeonResult.setTime((Long) time);
      Object session = pigeonVar_list.get(1);
      pigeonResult.setSession((String) session);
      Object protocol = pigeonVar_list.get(2);
      pigeonResult.setProtocol((Long) protocol);
      Object dport = pigeonVar_list.get(3);
      pigeonResult.setDport((Long) dport);
      Object ip = pigeonVar_list.get(4);
      pigeonResult.setIp((String) ip);
      Object host = pigeonVar_list.get(5);
      pigeonResult.setHost((String) host);
      Object packageName = pigeonVar_list.get(6);
      pigeonResult.setPackageName((String) packageName);
      Object size = pigeonVar_list.get(7);
      pigeonResult.setSize((Long) size);
      Object allowed = pigeonVar_list.get(8);
      pigeonResult.setAllowed((Boolean) allowed);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class Version {
    private @NonNull String version;

    public @NonNull String getVersion() {
      return version;
    }

    public void setVersion(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"version\" is null.");
      }
      this.version = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    Version() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      Version that = (Version) o;
      return version.equals(that.version);
    }

    @Override
    public int hashCode() {
      return Objects.hash(version);
    }

    public static final class Builder {

      private @Nullable String version;

      @CanIgnoreReturnValue
      public @NonNull Builder setVersion(@NonNull String setterArg) {
        this.version = setterArg;
        return this;
      }

      public @NonNull Version build() {
        Version pigeonReturn = new Version();
        pigeonReturn.setVersion(version);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(1);
      toListResult.add(version);
      return toListResult;
    }

    static @NonNull Version fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      Version pigeonResult = new Version();
      Object version = pigeonVar_list.get(0);
      pigeonResult.setVersion((String) version);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : RuleType.values()[((Long) value).intValue()];
        }
        case (byte) 130:
          return VpnConfig.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 131:
          return Application.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return ApplicationSetting.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return Packet.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return ResourceRecord.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 135:
          return Rule.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 136:
          return LogEntry.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 137:
          return ErrorLog.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 138:
          return SessionStatistics.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 139:
          return TrafficLog.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 140:
          return Version.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof RuleType) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((RuleType) value).index);
      } else if (value instanceof VpnConfig) {
        stream.write(130);
        writeValue(stream, ((VpnConfig) value).toList());
      } else if (value instanceof Application) {
        stream.write(131);
        writeValue(stream, ((Application) value).toList());
      } else if (value instanceof ApplicationSetting) {
        stream.write(132);
        writeValue(stream, ((ApplicationSetting) value).toList());
      } else if (value instanceof Packet) {
        stream.write(133);
        writeValue(stream, ((Packet) value).toList());
      } else if (value instanceof ResourceRecord) {
        stream.write(134);
        writeValue(stream, ((ResourceRecord) value).toList());
      } else if (value instanceof Rule) {
        stream.write(135);
        writeValue(stream, ((Rule) value).toList());
      } else if (value instanceof LogEntry) {
        stream.write(136);
        writeValue(stream, ((LogEntry) value).toList());
      } else if (value instanceof ErrorLog) {
        stream.write(137);
        writeValue(stream, ((ErrorLog) value).toList());
      } else if (value instanceof SessionStatistics) {
        stream.write(138);
        writeValue(stream, ((SessionStatistics) value).toList());
      } else if (value instanceof TrafficLog) {
        stream.write(139);
        writeValue(stream, ((TrafficLog) value).toList());
      } else if (value instanceof Version) {
        stream.write(140);
        writeValue(stream, ((Version) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface VpnController {

    void startVpn(@NonNull VpnConfig settings);

    void stopVpn();

    @NonNull 
    Boolean isRunning();

    @Nullable 
    VpnConfig getSession();

    void updateSettings(@NonNull VpnConfig settings);

    void updateStatsNotification(@NonNull SessionStatistics statistics);

    @NonNull 
    List<Application> getApplications();

    /** The codec used by VpnController. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `VpnController` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable VpnController api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable VpnController api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.startVpn" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                VpnConfig settingsArg = (VpnConfig) args.get(0);
                try {
                  api.startVpn(settingsArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.stopVpn" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  api.stopVpn();
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.isRunning" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  Boolean output = api.isRunning();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.getSession" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  VpnConfig output = api.getSession();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.updateSettings" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                VpnConfig settingsArg = (VpnConfig) args.get(0);
                try {
                  api.updateSettings(settingsArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.updateStatsNotification" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                SessionStatistics statisticsArg = (SessionStatistics) args.get(0);
                try {
                  api.updateStatsNotification(statisticsArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.pigeon_example_package.VpnController.getApplications" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  List<Application> output = api.getApplications();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class VpnEventHandler {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public VpnEventHandler(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public VpnEventHandler(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by VpnEventHandler.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void logText(@NonNull String messageArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logText" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(messageArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void logError(@NonNull String errorCodeArg, @NonNull String messageArg, @NonNull Object detailsArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Arrays.asList(errorCodeArg, messageArg, detailsArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void updateVpnState(@Nullable VpnConfig sessionArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.updateVpnState" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(sessionArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
    public void logTraffic(@NonNull TrafficLog logArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logTraffic" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(logArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
