// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    applicationSettingTable,
    rulesTable,
    hostsTable,
    settingsTable,
    resourceRecordTable,
    globalRuleSourceTable,
    trafficLogTable,
    hostRuleIndex,
    hostTypeIndex,
    package,
    indexDns,
    indexDnsResource,
    globalRuleTypeIndex,
    trafficLogSessionPackage,
    trafficLogPackageIp,
    trafficLogPackageHost,
    trafficLogPackageAllowed,
    trafficLogAllowed,
    trafficLogSessionTime,
  ];
  late final Shape0 applicationSettingTable = Shape0(
    source: i0.VersionedTable(
      entityName: 'application_setting_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(package_name)'],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 rulesTable = Shape1(
    source: i0.VersionedTable(
      entityName: 'rules_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_0,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 hostsTable = Shape2(
    source: i0.VersionedTable(
      entityName: 'hosts_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(rule_id, type, target)'],
      columns: [_column_12, _column_13, _column_9, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 settingsTable = Shape3(
    source: i0.VersionedTable(
      entityName: 'settings_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 resourceRecordTable = Shape4(
    source: i0.VersionedTable(
      entityName: 'resource_record_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 globalRuleSourceTable = Shape5(
    source: i0.VersionedTable(
      entityName: 'global_rule_source_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_4, _column_34, _column_9],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 trafficLogTable = Shape6(
    source: i0.VersionedTable(
      entityName: 'traffic_log_table',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_4,
        _column_28,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index hostRuleIndex = i1.Index(
    'hostRuleIndex',
    'CREATE INDEX hostRuleIndex ON hosts_table (rule_id)',
  );
  final i1.Index hostTypeIndex = i1.Index(
    'hostTypeIndex',
    'CREATE INDEX hostTypeIndex ON hosts_table (type)',
  );
  final i1.Index package = i1.Index(
    'package',
    'CREATE INDEX package ON rules_table (package_name)',
  );
  final i1.Index indexDns = i1.Index(
    'indexDns',
    'CREATE UNIQUE INDEX indexDns ON resource_record_table (q_name, a_name, resource)',
  );
  final i1.Index indexDnsResource = i1.Index(
    'indexDnsResource',
    'CREATE INDEX indexDnsResource ON resource_record_table (resource)',
  );
  final i1.Index globalRuleTypeIndex = i1.Index(
    'globalRuleTypeIndex',
    'CREATE INDEX globalRuleTypeIndex ON global_rule_source_table (type)',
  );
  final i1.Index trafficLogSessionPackage = i1.Index(
    'trafficLogSessionPackage',
    'CREATE INDEX trafficLogSessionPackage ON traffic_log_table (session, package_name)',
  );
  final i1.Index trafficLogPackageIp = i1.Index(
    'trafficLogPackageIp',
    'CREATE INDEX trafficLogPackageIp ON traffic_log_table (package_name, ip)',
  );
  final i1.Index trafficLogPackageHost = i1.Index(
    'trafficLogPackageHost',
    'CREATE INDEX trafficLogPackageHost ON traffic_log_table (package_name, host)',
  );
  final i1.Index trafficLogPackageAllowed = i1.Index(
    'trafficLogPackageAllowed',
    'CREATE INDEX trafficLogPackageAllowed ON traffic_log_table (package_name, allowed)',
  );
  final i1.Index trafficLogAllowed = i1.Index(
    'trafficLogAllowed',
    'CREATE INDEX trafficLogAllowed ON traffic_log_table (allowed)',
  );
  final i1.Index trafficLogSessionTime = i1.Index(
    'trafficLogSessionTime',
    'CREATE INDEX trafficLogSessionTime ON traffic_log_table (session, time)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get packageName =>
      columnsByName['package_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get filter =>
      columnsByName['filter']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get blockAll =>
      columnsByName['block_all']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get blockQuic =>
      columnsByName['block_quic']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'package_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_1(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'filter',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("filter" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_2(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'block_all',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("block_all" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_3(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'block_quic',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("block_quic" IN (0, 1))',
      ),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get packageName =>
      columnsByName['package_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get targetVersion =>
      columnsByName['target_version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get active =>
      columnsByName['active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get shouldBlockQuic =>
      columnsByName['should_block_quic']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get whitelistExclusive =>
      columnsByName['whitelist_exclusive']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target_version',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_8(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'active',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("active" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_10(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'should_block_quic',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("should_block_quic" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_11(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'whitelist_exclusive',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("whitelist_exclusive" IN (0, 1))',
      ),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get ruleId =>
      columnsByName['rule_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get target =>
      columnsByName['target']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rule_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES rules_table (id)',
      ),
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'target',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get darkMode =>
      columnsByName['dark_mode']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get colorScheme =>
      columnsByName['color_scheme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get includeSystemApps =>
      columnsByName['include_system_apps']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get logTraffic =>
      columnsByName['log_traffic']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get observeOnly =>
      columnsByName['observe_only']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<bool> get logCompactView =>
      columnsByName['log_compact_view']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get lastHostlistUpdate =>
      columnsByName['last_hostlist_update']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get analysisSettingsVolumeType =>
      columnsByName['analysis_settings_volume_type']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chartSettingsSorting =>
      columnsByName['chart_settings_sorting']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chartSettingsChartType =>
      columnsByName['chart_settings_chart_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get chartSettingsGroupType =>
      columnsByName['chart_settings_group_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get chartSettingsSingleBar =>
      columnsByName['chart_settings_single_bar']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<bool> _column_16(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'dark_mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("dark_mode" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'color_scheme',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_18(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'include_system_apps',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("include_system_apps" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_19(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'log_traffic',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("log_traffic" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_20(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'observe_only',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("observe_only" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<bool> _column_21(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'log_compact_view',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("log_compact_view" IN (0, 1))',
      ),
    );
i1.GeneratedColumn<DateTime> _column_22(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'last_hostlist_update',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'analysis_settings_volume_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chart_settings_sorting',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chart_settings_chart_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chart_settings_group_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_27(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'chart_settings_single_bar',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("chart_settings_single_bar" IN (0, 1))',
      ),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get time =>
      columnsByName['time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qName =>
      columnsByName['q_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get aName =>
      columnsByName['a_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get resource =>
      columnsByName['resource']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ttl =>
      columnsByName['ttl']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get uid =>
      columnsByName['uid']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'q_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'a_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'resource',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ttl',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'uid',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get time =>
      columnsByName['time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get session =>
      columnsByName['session']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get protocol =>
      columnsByName['protocol']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get packageName =>
      columnsByName['package_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ip =>
      columnsByName['ip']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get host =>
      columnsByName['host']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<bool> get allowed =>
      columnsByName['allowed']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'protocol',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'package_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ip',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'host',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<bool> _column_40(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'allowed',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("allowed" IN (0, 1))',
      ),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
