// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum RuleType {
  blacklist,
  whitelist,
}

/// MODELS
class VpnConfig {
  VpnConfig({
    required this.session,
    required this.filteredPackages,
    required this.dbPath,
    this.logTraffic = true,
    this.observeOnly = false,
    this.logLevel = 5,
  });

  /// Identifier for the session to allow matching traffic log to session
  String session;

  /// List of PackageNames that are filtered by the firewall
  List<String> filteredPackages;

  /// path of the sqlite database, so native code can read from it directly
  String dbPath;

  /// defines if the traffic should be logged. This enables analytics, but may increase battery usage.
  bool logTraffic;

  /// If this is set, the firewall does not block the traffic, but just observes it.
  /// It then logs whether or not it would usually block certain packets.
  /// Can be useful to understand the potential impact of the firewall.
  bool observeOnly;

  int logLevel;

  List<Object?> _toList() {
    return <Object?>[
      session,
      filteredPackages,
      dbPath,
      logTraffic,
      observeOnly,
      logLevel,
    ];
  }

  Object encode() {
    return _toList();  }

  static VpnConfig decode(Object result) {
    result as List<Object?>;
    return VpnConfig(
      session: result[0]! as String,
      filteredPackages: (result[1] as List<Object?>?)!.cast<String>(),
      dbPath: result[2]! as String,
      logTraffic: result[3]! as bool,
      observeOnly: result[4]! as bool,
      logLevel: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Application {
  Application({
    this.uid = -1,
    this.packageName = "",
    this.label = "",
    this.version = "",
    this.icon,
    this.system = false,
  });

  int uid;

  String packageName;

  String label;

  String version;

  Uint8List? icon;

  bool system;

  List<Object?> _toList() {
    return <Object?>[
      uid,
      packageName,
      label,
      version,
      icon,
      system,
    ];
  }

  Object encode() {
    return _toList();  }

  static Application decode(Object result) {
    result as List<Object?>;
    return Application(
      uid: result[0]! as int,
      packageName: result[1]! as String,
      label: result[2]! as String,
      version: result[3]! as String,
      icon: result[4] as Uint8List?,
      system: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Application || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ApplicationSetting {
  ApplicationSetting({
    required this.packageName,
    this.filter = false,
    this.blockAll = false,
    this.blockQuic = false,
  });

  String packageName;

  bool filter;

  bool blockAll;

  bool blockQuic;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      filter,
      blockAll,
      blockQuic,
    ];
  }

  Object encode() {
    return _toList();  }

  static ApplicationSetting decode(Object result) {
    result as List<Object?>;
    return ApplicationSetting(
      packageName: result[0]! as String,
      filter: result[1]! as bool,
      blockAll: result[2]! as bool,
      blockQuic: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApplicationSetting || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Packet {
  Packet({
    this.time = 0,
    this.version = 0,
    this.protocol = 0,
    this.flags = "",
    this.saddr = "",
    this.sport = 0,
    this.daddr = "",
    this.dport = 0,
    this.data = "",
    this.uid = 0,
    this.packageName,
    this.allowed = true,
  });

  int time;

  int version;

  int protocol;

  String flags;

  String saddr;

  int sport;

  String daddr;

  int dport;

  String data;

  int uid;

  String? packageName;

  bool allowed;

  List<Object?> _toList() {
    return <Object?>[
      time,
      version,
      protocol,
      flags,
      saddr,
      sport,
      daddr,
      dport,
      data,
      uid,
      packageName,
      allowed,
    ];
  }

  Object encode() {
    return _toList();  }

  static Packet decode(Object result) {
    result as List<Object?>;
    return Packet(
      time: result[0]! as int,
      version: result[1]! as int,
      protocol: result[2]! as int,
      flags: result[3]! as String,
      saddr: result[4]! as String,
      sport: result[5]! as int,
      daddr: result[6]! as String,
      dport: result[7]! as int,
      data: result[8]! as String,
      uid: result[9]! as int,
      packageName: result[10] as String?,
      allowed: result[11]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Packet || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ResourceRecord {
  ResourceRecord({
    this.time = 0,
    this.qName = "",
    this.aName = "",
    this.resource = "",
    this.ttl,
    this.uid,
    this.packageName,
  });

  int time;

  String qName;

  String aName;

  String resource;

  int? ttl;

  int? uid;

  String? packageName;

  List<Object?> _toList() {
    return <Object?>[
      time,
      qName,
      aName,
      resource,
      ttl,
      uid,
      packageName,
    ];
  }

  Object encode() {
    return _toList();  }

  static ResourceRecord decode(Object result) {
    result as List<Object?>;
    return ResourceRecord(
      time: result[0]! as int,
      qName: result[1]! as String,
      aName: result[2]! as String,
      resource: result[3]! as String,
      ttl: result[4] as int?,
      uid: result[5] as int?,
      packageName: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ResourceRecord || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Rule {
  Rule({
    this.packageName,
    required this.type,
    required this.shouldBlockQuic,
    required this.whitelistExclusive,
    required this.hosts,
    required this.ips,
  });

  String? packageName;

  RuleType type;

  bool shouldBlockQuic;

  bool whitelistExclusive;

  Map<String, bool> hosts;

  Map<String, bool> ips;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
      type,
      shouldBlockQuic,
      whitelistExclusive,
      hosts,
      ips,
    ];
  }

  Object encode() {
    return _toList();  }

  static Rule decode(Object result) {
    result as List<Object?>;
    return Rule(
      packageName: result[0] as String?,
      type: result[1]! as RuleType,
      shouldBlockQuic: result[2]! as bool,
      whitelistExclusive: result[3]! as bool,
      hosts: (result[4] as Map<Object?, Object?>?)!.cast<String, bool>(),
      ips: (result[5] as Map<Object?, Object?>?)!.cast<String, bool>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Rule || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LogEntry {
  LogEntry({
    required this.time,
    required this.session,
    required this.data,
  });

  int time;

  String session;

  Object data;

  List<Object?> _toList() {
    return <Object?>[
      time,
      session,
      data,
    ];
  }

  Object encode() {
    return _toList();  }

  static LogEntry decode(Object result) {
    result as List<Object?>;
    return LogEntry(
      time: result[0]! as int,
      session: result[1]! as String,
      data: result[2]!,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LogEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ErrorLog {
  ErrorLog({
    required this.time,
    required this.session,
    this.message = "Error",
  });

  int time;

  String session;

  String message;

  List<Object?> _toList() {
    return <Object?>[
      time,
      session,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static ErrorLog decode(Object result) {
    result as List<Object?>;
    return ErrorLog(
      time: result[0]! as int,
      session: result[1]! as String,
      message: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ErrorLog || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SessionStatistics {
  SessionStatistics({
    this.packetCountAllowed = 0,
    this.packetSizeAllowed = 0,
    this.packetCountBlocked = 0,
    this.packetSizeBlocked = 0,
    this.mostBlockedPackage,
    this.mostTrafficPackage,
  });

  int packetCountAllowed;

  int packetSizeAllowed;

  int packetCountBlocked;

  int packetSizeBlocked;

  String? mostBlockedPackage;

  String? mostTrafficPackage;

  List<Object?> _toList() {
    return <Object?>[
      packetCountAllowed,
      packetSizeAllowed,
      packetCountBlocked,
      packetSizeBlocked,
      mostBlockedPackage,
      mostTrafficPackage,
    ];
  }

  Object encode() {
    return _toList();  }

  static SessionStatistics decode(Object result) {
    result as List<Object?>;
    return SessionStatistics(
      packetCountAllowed: result[0]! as int,
      packetSizeAllowed: result[1]! as int,
      packetCountBlocked: result[2]! as int,
      packetSizeBlocked: result[3]! as int,
      mostBlockedPackage: result[4] as String?,
      mostTrafficPackage: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SessionStatistics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class TrafficLog {
  TrafficLog({
    required this.time,
    required this.session,
    this.protocol = 0,
    this.dport = 0,
    this.ip = "",
    this.host,
    this.packageName,
    this.size = 0,
    required this.allowed,
  });

  int time;

  String session;

  int protocol;

  int dport;

  String ip;

  String? host;

  String? packageName;

  int size;

  bool allowed;

  List<Object?> _toList() {
    return <Object?>[
      time,
      session,
      protocol,
      dport,
      ip,
      host,
      packageName,
      size,
      allowed,
    ];
  }

  Object encode() {
    return _toList();  }

  static TrafficLog decode(Object result) {
    result as List<Object?>;
    return TrafficLog(
      time: result[0]! as int,
      session: result[1]! as String,
      protocol: result[2]! as int,
      dport: result[3]! as int,
      ip: result[4]! as String,
      host: result[5] as String?,
      packageName: result[6] as String?,
      size: result[7]! as int,
      allowed: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrafficLog || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class Version {
  Version({
    required this.version,
  });

  String version;

  List<Object?> _toList() {
    return <Object?>[
      version,
    ];
  }

  Object encode() {
    return _toList();  }

  static Version decode(Object result) {
    result as List<Object?>;
    return Version(
      version: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! Version || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is RuleType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VpnConfig) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is Application) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ApplicationSetting) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is Packet) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ResourceRecord) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is Rule) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is LogEntry) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ErrorLog) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is SessionStatistics) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is TrafficLog) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is Version) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RuleType.values[value];
      case 130: 
        return VpnConfig.decode(readValue(buffer)!);
      case 131: 
        return Application.decode(readValue(buffer)!);
      case 132: 
        return ApplicationSetting.decode(readValue(buffer)!);
      case 133: 
        return Packet.decode(readValue(buffer)!);
      case 134: 
        return ResourceRecord.decode(readValue(buffer)!);
      case 135: 
        return Rule.decode(readValue(buffer)!);
      case 136: 
        return LogEntry.decode(readValue(buffer)!);
      case 137: 
        return ErrorLog.decode(readValue(buffer)!);
      case 138: 
        return SessionStatistics.decode(readValue(buffer)!);
      case 139: 
        return TrafficLog.decode(readValue(buffer)!);
      case 140: 
        return Version.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class VpnController {
  /// Constructor for [VpnController].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpnController({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> startVpn(VpnConfig settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.startVpn$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> stopVpn() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.stopVpn$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isRunning() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.isRunning$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<VpnConfig?> getSession() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.getSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as VpnConfig?);
    }
  }

  Future<void> updateSettings(VpnConfig settings) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.updateSettings$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[settings]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateStatsNotification(SessionStatistics statistics) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.updateStatsNotification$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[statistics]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<Application>> getApplications() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.pigeon_example_package.VpnController.getApplications$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<Application>();
    }
  }
}

abstract class VpnEventHandler {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void logText(String message);

  void logError(String errorCode, String message, Object details);

  void updateVpnState(VpnConfig? session);

  Future<void> logTraffic(TrafficLog log);

  static void setUp(VpnEventHandler? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logText$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logText was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_message = (args[0] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logText was null, expected non-null String.');
          try {
            api.logText(arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_errorCode = (args[0] as String?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError was null, expected non-null String.');
          final String? arg_message = (args[1] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError was null, expected non-null String.');
          final Object? arg_details = (args[2] as Object?);
          assert(arg_details != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logError was null, expected non-null Object.');
          try {
            api.logError(arg_errorCode!, arg_message!, arg_details!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.updateVpnState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.updateVpnState was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final VpnConfig? arg_session = (args[0] as VpnConfig?);
          try {
            api.updateVpnState(arg_session);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logTraffic$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logTraffic was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final TrafficLog? arg_log = (args[0] as TrafficLog?);
          assert(arg_log != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.VpnEventHandler.logTraffic was null, expected non-null TrafficLog.');
          try {
            await api.logTraffic(arg_log!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
